version: '3.8'
services:
  prisma:
    build: ./infrastructure/prisma
    ports:
      - "5555:5555"
    environment:
      # Utiliser la variable d'environnement pour la connexion à la BDD
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./infrastructure/prisma:/app/prisma
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      # Utiliser les variables d'environnement pour la configuration PostgreSQL
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"


  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"


