version: '3.8'
services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      # Utiliser la variable d'environnement pour la connexion à la BDD
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    networks:
      - app-network
    command: bash -c "npx prisma generate && npm run start"

  db:
    image: postgres:15
    restart: always
    environment:
      # Utiliser les variables d'environnement pour la configuration PostgreSQL
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
