version: '3.8'
services:
  prisma:
    build: ./infrastructure/adapters/repositories/prisma
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./infrastructure/adapters/repositories/prisma:/app/infrastructure/adapters/repositories/prisma
    depends_on:
      - db

  graphql:
      build: ./infrastructure/platforms/graphql
      ports:
        - "4000:4000"
      environment:
        DATABASE_URL: ${DATABASE_URL}
      volumes:
        - ./infrastructure/platforms/graphql:/app/infrastructure/platforms/graphql
      depends_on:
        - db

  db:
    image: postgres:15
    restart: always
    environment:
      # Utiliser les variables d'environnement pour la configuration PostgreSQL
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"


  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"


